/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        outline: '#76777d',
        'surface-container-low': '#f2f4f6',
        'primary-fixed-dim': '#bec6e0',
        'on-error': '#ffffff',
        'on-surface-variant': '#45464d',
        'surface-bright': '#f7f9fb',
        'on-primary-fixed-variant': '#3f465c',
        'surface-container': '#eceef0',
        'inverse-primary': '#bec6e0',
        'on-tertiary': '#ffffff',
        'on-primary-fixed': '#131b2e',
        'surface-variant': '#e0e3e5',
        'on-secondary-fixed': '#002113',
        'primary-container': '#131b2e',
        'tertiary-fixed': '#ffdada',
        background: '#f7f9fb',
        'surface-container-highest': '#e0e3e5',
        primary: '#000000',
        'on-background': '#191c1e',
        error: '#ba1a1a',
        'outline-variant': '#c6c6cd',
        'on-tertiary-fixed-variant': '#920028',
        'surface-container-lowest': '#ffffff',
        'on-secondary-fixed-variant': '#005236',
        'surface-tint': '#565e74',
        tertiary: '#000000',
        'on-error-container': '#93000a',
        'on-primary-container': '#7c839b',
        'tertiary-container': '#40000c',
        'surface-container-high': '#e6e8ea',
        'on-secondary-container': '#00714d',
        'on-surface': '#191c1e',
        'on-secondary': '#ffffff',
        'on-tertiary-fixed': '#40000c',
        'tertiary-fixed-dim': '#ffb3b6',
        'secondary-fixed-dim': '#4edea3',
        'secondary-fixed': '#6ffbbe',
        'inverse-on-surface': '#eff1f3',
        'inverse-surface': '#2d3133',
        'primary-fixed': '#dae2fd',
        surface: '#f7f9fb',
        'surface-dim': '#d8dadc',
        'secondary-container': '#6cf8bb',
        'error-container': '#ffdad6',
        'on-primary': '#ffffff',
        'on-tertiary-container': '#f83256',
        'sos-red': '#FF4D4D',
        'deep-navy': '#131b2e',
        'mockup-purple': '#635BFF',
        secondary: '#006c49',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      spacing: {
        'margin-mobile': '1rem',
        'margin-desktop': '3rem',
        gutter: '1.5rem',
        'stack-sm': '0.5rem',
        'stack-md': '1rem',
        'stack-lg': '2rem',
        'stack-xl': '4rem',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['4rem', { lineHeight: '4.5rem', letterSpacing: '-0.02em', fontWeight: '800' }],
        'display-lg-mobile': ['2.5rem', { lineHeight: '3rem', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-xl': ['3rem', { lineHeight: '3.5rem', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg': ['2rem', { lineHeight: '2.5rem', fontWeight: '700' }],
        'headline-md': ['1.5rem', { lineHeight: '2rem', fontWeight: '600' }],
        'body-lg': ['1.25rem', { lineHeight: '1.875rem', fontWeight: '400' }],
        'body-md': ['1rem', { lineHeight: '1.5rem', fontWeight: '400' }],
        'label-md': ['0.875rem', { lineHeight: '1.25rem', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-sm': ['0.75rem', { lineHeight: '1rem', fontWeight: '500' }],
      },
      animation: {
        'pulse-red': 'pulse-red 2s infinite ease-in-out',
      },
      keyframes: {
        'pulse-red': {
          '0%, 100%': { transform: 'scale(1)', opacity: '1' },
          '50%': { transform: 'scale(1.05)', opacity: '0.9' },
        },
      },
    },
  },
  plugins: [],
};
